/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => main_default
});
module.exports = __toCommonJS(main_exports);

// modules/SyncPlugin.ts
var import_obsidian3 = require("obsidian");

// modules/settings.ts
var DEFAULT_CONFIG_FOLDER_PATH = ".obsidian";
var DEFAULT_COMMON_FOLDER_PATH = "./configBackupFolder";
var DEFAULT_INTERVAL = 0;
var DEFAULT_SETTINGS = {
  configFolderPath: DEFAULT_CONFIG_FOLDER_PATH,
  commonFolderPath: DEFAULT_COMMON_FOLDER_PATH,
  autoSaveInterval: DEFAULT_INTERVAL
};

// modules/SyncModal.ts
var import_obsidian = require("obsidian");
var SyncModal = class extends import_obsidian.Modal {
  constructor(app, syncModel, plugin) {
    super(app);
    this.syncModel = syncModel;
    this.plugin = plugin;
  }
  get configFolder() {
    const p = (0, import_obsidian.normalizePath)(this.plugin.settings.configFolderPath || this.app.vault.configDir);
    return p.endsWith("/") ? p.substring(0, p.length - 1) : p;
  }
  get commonFolder() {
    const p = (0, import_obsidian.normalizePath)(this.plugin.settings.commonFolderPath);
    return p.endsWith("/") ? p.substring(0, p.length - 1) : p;
  }
  logNormal(text, contentEl) {
    if (contentEl) {
      contentEl.createDiv({ text });
    } else {
      new import_obsidian.Notice(text, 3e3);
    }
  }
  logSuccess(text, contentEl) {
    if (contentEl) {
      contentEl.createDiv({ text, attr: { style: "color: green;" } });
    } else {
      const fragment = document.createDocumentFragment();
      fragment.appendChild(
        fragment.createSpan({
          text,
          attr: {
            style: "color: green;"
          }
        })
      );
      new import_obsidian.Notice(fragment, 3e3);
    }
  }
  logFail(text, contentEl) {
    if (contentEl) {
      contentEl.createDiv({ text, attr: { style: "color: red;" } });
    } else {
      const fragment = document.createDocumentFragment();
      fragment.appendChild(
        fragment.createSpan({
          text,
          attr: {
            style: "color: red;"
          }
        })
      );
      new import_obsidian.Notice(fragment, 0);
    }
  }
  async syncConfig(contentEl) {
    try {
      this.logNormal("Check if ConfigFolder exists (\u68C0\u67E5 ConfigFolder \u662F\u5426\u5B58\u5728) ...", contentEl);
      const isConfigFolderExisted = await this.app.vault.adapter.exists(this.configFolder, true);
      if (!isConfigFolderExisted) {
        this.logSuccess("ConfigFolder does not exist, no need to back up (ConfigFolder \u4E0D\u5B58\u5728\uFF0C\u65E0\u9700\u5907\u4EFD) .", contentEl);
        return;
      }
      this.logNormal("Reset CommonFolder (\u91CD\u7F6E CommonFolder \u4E2D) ...", contentEl);
      const isCommonFolderExisted = await this.app.vault.adapter.exists(this.commonFolder, true);
      if (isCommonFolderExisted) {
        await this.app.vault.adapter.rmdir(this.commonFolder, true);
      }
      await this.app.vault.adapter.mkdir(this.commonFolder);
      this.logSuccess("Reset CommonFolder successfully (\u91CD\u7F6E CommonFolder \u6210\u529F) .", contentEl);
      this.logNormal("Back up ConfigFolder (\u5907\u4EFD ConfigFolder \u4E2D) ...", contentEl);
      await this.recursiveCopy(this.configFolder, this.commonFolder);
      this.logSuccess("Backup ConfigFolder successful (\u5907\u4EFD ConfigFolder \u6210\u529F) .", contentEl);
    } catch (e) {
      this.logFail(e.message, contentEl);
    }
  }
  async restoreConfig(contentEl) {
    try {
      this.logNormal("Check if CommonFolder exists (\u68C0\u67E5 CommonFolder \u662F\u5426\u5B58\u5728) ...", contentEl);
      const isCommonFolderExisted = await this.app.vault.adapter.exists(this.commonFolder, true);
      if (!isCommonFolderExisted) {
        this.logSuccess("CommonFolder does not exist and cannot be restored (CommonFolder \u4E0D\u5B58\u5728\uFF0C\u65E0\u6CD5\u6062\u590D) .", contentEl);
        return;
      }
      this.logNormal("Reset ConfigFolder (\u91CD\u7F6E ConfigFolder \u4E2D) ...", contentEl);
      const isConfigFolderExisted = await this.app.vault.adapter.exists(this.configFolder, true);
      if (isConfigFolderExisted) {
        await this.app.vault.adapter.rmdir(this.configFolder, true);
      }
      await this.app.vault.adapter.mkdir(this.configFolder);
      this.logSuccess("Reset ConfigFolder successfully (\u91CD\u7F6E ConfigFolder \u6210\u529F) .", contentEl);
      this.logNormal("Restore ConfigFolder (\u6062\u590D ConfigFolder \u4E2D) ...", contentEl);
      await this.recursiveCopy(this.commonFolder, this.configFolder);
      this.logSuccess("Restore ConfigFolder successfully (\u6062\u590D ConfigFolder \u6210\u529F) .", contentEl);
    } catch (e) {
      this.logFail(e.message, contentEl);
    }
  }
  onOpen() {
    window.setTimeout(() => {
      const { contentEl } = this;
      if (this.syncModel === 2 /* Restore */) {
        this.restoreConfig(contentEl);
        return;
      }
      this.syncConfig(contentEl);
    }, 300);
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
  async recursiveCopy(src, dest) {
    const stat = await this.app.vault.adapter.stat(src);
    if ((stat == null ? void 0 : stat.type) === "folder" /* Folder */) {
      if (!await this.app.vault.adapter.exists(dest, true)) {
        await this.app.vault.adapter.mkdir(dest);
      }
      const { folders, files } = await this.app.vault.adapter.list(src);
      await Promise.all([...folders, ...files].map(async (item) => {
        await this.recursiveCopy(item, item.replace(src, dest));
      }));
      return;
    }
    await this.app.vault.adapter.copy(src, dest);
  }
};

// modules/SyncSettingTab.ts
var import_obsidian2 = require("obsidian");
var SyncSettingTab = class extends import_obsidian2.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian2.Setting(containerEl).setName("Config folder path").setDesc("Customize the path filled in ConfigFolder, which needs to be consistent with the one in Files and links->Override config folder (\u81EA\u5B9A\u4E49\u586B\u5165 ConfigFolder \u7684\u8DEF\u5F84\uFF0C\u9700\u8981\u548C \u6587\u4EF6\u4E0E\u94FE\u63A5->\u5207\u6362\u914D\u7F6E\u6587\u4EF6\u5939 \u4E2D\u7684\u4FDD\u6301\u4E00\u81F4)").addText((text) => text.setPlaceholder(DEFAULT_CONFIG_FOLDER_PATH).setValue(this.plugin.settings.configFolderPath).onChange(async (value) => {
      this.plugin.settings.configFolderPath = value || DEFAULT_CONFIG_FOLDER_PATH;
      await this.plugin.saveSettings();
    }));
    new import_obsidian2.Setting(containerEl).setName("Common folder path").setDesc("Customize the path to be filled in ConfigFolder for synchronization. The relative path needs to start with ./ or ../ (\u81EA\u5B9A\u4E49\u586B\u5165 ConfigFolder \u540C\u6B65\u7684\u8DEF\u5F84\uFF0C\u76F8\u5BF9\u8DEF\u5F84\u9700\u8981\u4EE5 ./ \u6216\u8005 ../ \u5F00\u5934)").addText((text) => text.setPlaceholder(DEFAULT_COMMON_FOLDER_PATH).setValue(this.plugin.settings.commonFolderPath).onChange(async (value) => {
      this.plugin.settings.commonFolderPath = value || DEFAULT_COMMON_FOLDER_PATH;
      await this.plugin.saveSettings();
    }));
    new import_obsidian2.Setting(containerEl).setName("Auto save interval").setDesc("Customize the auto save time interval in seconds, 0 means off (\u81EA\u5B9A\u4E49\u81EA\u52A8\u4FDD\u5B58\u7684\u65F6\u95F4\u95F4\u9694\uFF0C\u5355\u4F4D\u662F\u79D2\uFF0C0 \u4EE3\u8868\u5173\u95ED). Need to be restarted to take effect (\u4FEE\u6539\u90FD\u9700\u8981\u91CD\u542F\u751F)").addText((text) => text.setPlaceholder(String(DEFAULT_INTERVAL)).setValue(String(this.plugin.settings.autoSaveInterval)).onChange(async (value) => {
      this.plugin.settings.autoSaveInterval = Number(value) || DEFAULT_INTERVAL;
      await this.plugin.saveSettings();
    }));
  }
};

// modules/SyncPlugin.ts
var SyncPlugin = class extends import_obsidian3.Plugin {
  async onload() {
    await this.loadSettings();
    this.addCommand({
      id: "sync-config-folder-to-common-folder",
      name: "Sync",
      callback: () => {
        new SyncModal(this.app, 1 /* Sync */, this).open();
      }
    });
    this.addCommand({
      id: "restore-config-folder-from-common-folder",
      name: "Restore",
      callback: () => {
        new SyncModal(this.app, 2 /* Restore */, this).open();
      }
    });
    this.addSettingTab(new SyncSettingTab(this.app, this));
    if (this.settings.autoSaveInterval) {
      this.registerInterval(window.setInterval(
        () => {
          new SyncModal(this.app, 0 /* None */, this).syncConfig();
        },
        this.settings.autoSaveInterval * 1e3
      ));
    }
  }
  onunload() {
  }
  async loadSettings() {
    const originData = await this.loadData();
    this.settings = Object.assign({}, DEFAULT_SETTINGS, originData);
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
};

// main.ts
var main_default = SyncPlugin;
